apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-sidecar
  template:
    metadata:
      labels:
        app: nginx-with-sidecar
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: log-volume
          mountPath: /var/custom
      - name: log-tailer
        image: busybox:latest
        command:
          - "sh"
          - "-c"
          - >
            (
              tail -n +1 -F /var/custom/app1-custom.log | awk '{print "vishal-app", $0}' &
              tail -n +1 -F /var/custom/app2-custom.log | awk '{print "vishal-app", $0}' &
              tail -n +1 -F /var/custom/app3-custom.log | awk '{print "vishal-app", $0}' &
              tail -n +1 -F /var/custom/app4-custom.log | awk '{print "xyz-app", $0}' &
              tail -n +1 -F /var/custom/app5-custom.log | awk '{print "xyz-app", $0}' &
              tail -n +1 -F /var/vishal/vishal-custom.log | awk '{print "vishal-custom-app", $0}' &
              tail -n +1 -F /var/vishal/vishal-custom.log | awk '{print "vishal-custom-app", $0}' &
            ) | cat
        volumeMounts:
        - name: log-volume
          mountPath: /var/custom
        - name: log-vishal
          mountPath: /var/vishal
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: log-vishal
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-with-sidecar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
